In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("kidney_disease.csv")
quan=[]
qual=[]
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [3]:
#Assigning dataset to dataframe for Dropping the id column which is not necessary for analysis
df=pd.DataFrame(dataset)
dfid=pd.DataFrame(dataset['id'])

In [4]:
df=df.drop(["id"],axis=1)
dataset=df

In [5]:
#Splitting numerical and categorical data
from Univariatekidney import univar
u=univar(dataset)
qual,quan=u.quanqual()

In [6]:
# In the dataset PCV,RC,WC are  umeric values but its typr is object so it is been converted to numeric value
dataset['pcv']=pd.to_numeric(dataset['pcv'],errors='coerce')
dataset['wc']=pd.to_numeric(dataset['wc'],errors='coerce')
dataset['rc']=pd.to_numeric(dataset['rc'],errors='coerce')

In [7]:
#Finding the null values
dataset.isnull().sum()

age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                71
wc                106
rc                131
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [8]:
#Assigining median values to null values of numrical data
from sklearn.impute import SimpleImputer
impute=SimpleImputer(missing_values=np.nan,strategy="median")
impute=impute.fit(dataset[quan])
imtable=pd.DataFrame(impute.transform(dataset[quan]).round(2))
dataset[quan]=imtable

In [9]:
#Assigining median values to null values of categorical data
from sklearn.impute import SimpleImputer
impute=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
impute=impute.fit(dataset[qual])
imptable=pd.DataFrame(impute.transform(dataset[qual]))
dataset[qual]=imptable

In [10]:
#Inserting the id column which has been dropped initially
df.insert(0,"id",dfid)
dataset=df

In [11]:
# saving preprocessed data to new csv file
dataset.to_csv("prekidney.csv",index=False)

In [12]:
#Reading Preprocessed CSV file
dataset=pd.read_csv("prekidney.csv") #Reading Preprocessed CSV file

In [13]:
dataset.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64